Update check.yml (#123)

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -109,7 +109,6 @@ jobs:
       - name: Add translation keys
         run: |
           cd ${{ env.BRANCH_PATH }}
-          ls
           git add .
           git diff --staged --quiet || echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
           git commit -m "Update translation files" || echo "No changes to commit"
@@ -117,4 +116,4 @@ jobs:
         if: env.CHANGES_DETECTED == 'true'
         run: |
           cd ${{ env.BRANCH_PATH }}
-          git push origin ${{ env.BRANCH_PATH }}
+          git push origin ${{ env.BRANCH_PATH }} || echo "Push failed: possibly no changes to push"
